#!/bin/bash

intltool-extract --type=gettext/glade usr/share/linuxmint/mintwelcome/mintwelcome.ui
xgettext --language=Python --keyword=_ --keyword=N_ --output=mintwelcome.pot usr/lib/elderberrylinux/elderwelcome/elderwelcome.py generate_desktop_files usr/share/elderberrylinux/elderwelcome/elderwelcome.ui.h
rm -f usr/share/elderberrylinux/elderwelcome/elderwelcome.ui.h
